### ISSUE TITLE
children and childNodes should not be identical

### ISSUE THREAD

**Issue by Zirak** [fb55/domhandler#24]
Currently, `children` and `childNodes` refer to the same thing, which is what browser-DOM calls `childNodes`. That's not spec compliant - `children` is an `HTMLCollection` containing only elements, without things like text nodes and comments ([spec](https://dom.spec.whatwg.org/#dom-parentnode-children)).

I can PR this if you're interested; while it breaks backwards-compat with this library, it's breaking compliance to spec, and surprised me quite a bit.

**Comment by fb55** [comment]
The current dom structure is a relict from the `htmlparser` project and I would like to avoid breaking changes. `childNodes` is already an added property to combine both structures, but I agree that `children` is unfortunate. Perhaps this project could be forked at some point as a better implementation of a lightweight DOM for cheerio.
