### ISSUE TITLE
Warning about mutating [[Prototype]] of elements Objects

### ISSUE THREAD

**Issue by Delgan** [fb55/domhandler#27]
Hello.

Using Firefox and others libraries which make use of `domhandler`, the following warning message is sometimes prompted into the console:

`: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`

This comes from [these lines](https://github.com/fb55/domhandler/blob/7dedb4dc754d5d340310de0695c4711b2883f1b8/index.js#L74-L76):

``` javascript
if (this._options.withDomLvl1) {
    element.__proto__ = element.type === "tag" ? ElementPrototype : NodePrototype;
}
```

More information about this warning can be found on the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto) or in [this SO question](http://stackoverflow.com/questions/23807805/why-is-mutating-the-prototype-of-an-object-bad-for-performance/23809148#23809148).

I would like to know if you was aware about this and if you thought it might need a fix, or is it an intended choice to implement the prototype mutation like this?

**Comment by fb55** [comment]
The current state is only intended to be temporary, I'd like to switch to DOM Level 1 names entirely in a future release. Moving this to the object literal wouldn't hurt, PRs welcome :)
