### ISSUE TITLE
Why AST different between parse5(as expected) and htmlparser2(not as expected)?

### ISSUE THREAD

**Issue by StinsonZhao** [fb55/domhandler#273]
```html
<em>hello</em> world
```

In **htmlparser2**:
<img width="993" alt="Xnip2020-06-02_18-17-49" src="https://user-images.githubusercontent.com/6703905/83509444-0625a400-a4fe-11ea-94b5-952df2130dcf.png">

But in **parse5**:
<img width="1303" alt="Xnip2020-06-02_18-23-07" src="https://user-images.githubusercontent.com/6703905/83509508-1f2e5500-a4fe-11ea-9284-f509fc07c16a.png">

I think the result AST **parse5** outputs is as expected?

**Comment by fb55** [comment]
Transferred to `domhandler`, as this seems to be the problematic project.

**Comment by fb55** [comment]
Added a test case in 593d944. It looks like htmlparser2 and domhandler are producing the expected output, I suspect AST Explorer is the culprit here (cc @fkling).

**Comment by fkling** [comment]
Our implementation seems to extend `DomHandler`. It's possible that that causes some issues. I'll investigate.
