### ISSUE TITLE
patch release - Add npmignore test

### ISSUE THREAD

**Issue by david-fong** [fb55/domhandler#425]
The fix made in #51 hasn't been applied to major version 2 of this package. It would be nice for a version 2.4.3 to be published with such a fix as well so that dependents of v2 can also reap the benefit.

**Comment by fb55** [comment]
There is a `files` field in the `package.json`. If you look at the bundle on NPM, there is only a small number of files here: https://unpkg.com/browse/domhandler@4.0.0/

`domhandler` should be pretty easy to migrate to the latest version. Older versions will not see updates unless they are addressing security issues.
