### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by ad-venture** [fb55/domhandler#43]
Hi

I'm using your great product, and I really need the new "EndIndices" feature.
I'm using the code as an npm package, but currently, I must direct my config file to the git himself due to the un-updated version in the npm.

Can you please update the npm package to the latest version?

Many thanks
Ysrael

**Comment by thomas-darling** [comment]
@fb55
We **really** need this too, and we can't just install this from the Github `master`, as this is actually a dependency of another library we are using. Can you please publish a new version to NPM, including the "withEndIndices" feature that was added in commit https://github.com/fb55/domhandler/commit/654e1be73348605063aaee2c31168922b9bb7b87?

**Comment by fb55** [comment]
Just released a new version.

**Comment by thomas-darling** [comment]
Thanks, much appreciated :-)
