### ISSUE TITLE
Feature request: attribs indices

### ISSUE THREAD

**Issue by droooney** [fb55/domhandler#46]
Could it be done that, with `withStartIndices` and `withEndIndices` set, a node had `attribsIndices` property (or something like that) that would contain atributes names and values start and end indices?

It also would be great to have not only offsets but line and column numbers as well.

**Comment by fb55** [comment]
This doesn't work with the current format of the attributes in the dom (as object properties), but you are already able to get attribute indexes when directly observing the parser.
