### ISSUE TITLE
version 4.2.0 error

### ISSUE THREAD

**Issue by luizeof** [fb55/domhandler#506]
```bash
$ npm update             
npm ERR! code ETARGET
npm ERR! notarget No matching version found for domhandler@^4.2.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by veranika-savanchuk** [comment]
the same issue

**Comment by sallar** [comment]
Same thing happened to me. I was wondering what exactly happened to my CI builds, since I didnt make any changes to the actual source code. Turns out `expo-cli` depends on `domhandler` and this new version killed it.

**Comment by fb55** [comment]
`npm` might take a minute to distribute new versions. Based on the comment in https://github.com/expo/expo-github-action/issues/80, I assume this has been resolved.

**Comment by luizeof** [comment]
thanks @fb55 ;)
