### ISSUE TITLE
Feature request: Identify missing ending tags

### ISSUE THREAD

**Issue by matthewp** [fb55/domhandler#52]
With a document such as this:

```html
<!doctype html>
<html lang="en">
<title>My Document</title>
<h1>Title</h1>
```

Notice that it is missing the `</html>` end tag. Since this tag is optional I often omit it. It would be great if domhandler had some way to indicate that a tag is missing the ending. Something like `closing: false` would suffice.

**Comment by fb55** [comment]
This seems like a workaround for something that could be achieved in a way more reliable way by using an HTML minimizer.
