### ISSUE TITLE
"attribs" is an uncomfortable compromise between "attributes" and "attrs"

### ISSUE THREAD

**Issue by servel333** [fb55/domhandler#53]
This could very well be a 'close, won't fix' issue, and if so, that's ok.

But, I wanted to point out how unusual it is to use `attribs` as the property name that stores HTML attributes. I would much prefer `attrs` or `attributes`. If this could be changed, it would be nice.

Like I said though, I understand how complex it can be to change after release.

**Comment by fb55** [comment]
I agree that this isn't ideal. This was inherited from the original `node-htmlparser` project, and given that a lot of projects depend on it, changing it isn't an option.

**Comment by servel333** [comment]
That's fair. Thanks.
