### ISSUE TITLE
[QUESTION] Is there possible to manipulate Dom in DomHandler callback?

### ISSUE THREAD

**Issue by Genuifx** [fb55/domhandler#60]
Is there possible to manipulate Dom in DomHandler callback? like babal's Path in it's AST tree?

**Comment by fb55** [comment]
Not sure if this is answering your question: The third argument of domhandler's constructor is an `elementCB`, which can be used to get notified once an element and all of its children have been added to the DOM (while the DOM is still being built). You can traverse the parent elements using the `.parent` property.

**Comment by Genuifx** [comment]
Not exactly, but I get that I can still use iterate to manipulate DOM
