### ISSUE TITLE
Is there a way to "keepClosingSlash: true"

### ISSUE THREAD

**Issue by dhlolo** [fb55/domhandler#678]
rawHtml:
<wxs ... />...

result:
<wxs ...>...</wxs>

**Comment by fb55** [comment]
`xmlMode: true`?

**Comment by dhlolo** [comment]
seems not work

**Comment by dhlolo** [comment]
code:
reusltStr = render(dom, { xmlMode: true, selfClosingTags: true });

**Comment by dhlolo** [comment]
et handler = new DomHandler((error, dom) => {
    if (error) {
        // Handle error
    } else {
        // find(ele => {
        //     const rawClass = getAttributeValue(ele, 'class');
        //     const newValue = replaceClassName(rawClass, styleMap);
        //     if (newValue !== rawClass) {
        //         ele.attribs.class = newValue;
        //         needReplace = true;
        //     }
        // }, dom, true);
        console.log('===dom', dom);
        reusltStr = render(dom, { xmlMode: true });
    }
}, {
    xmlMode: true
});
let wxmlParser = new Parser(handler);
wxmlParser.write(file);
wxmlParser.end();

**Comment by dhlolo** [comment]
`et handler = new DomHandler((error, dom) => {
    if (error) {
        // Handle error
    } else {
        // find(ele => {
        //     const rawClass = getAttributeValue(ele, 'class');
        //     const newValue = replaceClassName(rawClass, styleMap);
        //     if (newValue !== rawClass) {
        //         ele.attribs.class = newValue;
        //         needReplace = true;
        //     }
        // }, dom, true);
        console.log('===dom', dom);
        reusltStr = render(dom, { xmlMode: true });
    }
}, {
    xmlMode: true
});
let wxmlParser = new Parser(handler);
wxmlParser.write(file);
wxmlParser.end();`

**Comment by dhlolo** [comment]
let handler = new DomHandler((error, dom) => {
    if (error) {
        // Handle error
    } else {
        console.log('===dom', dom);
        reusltStr = render(dom, { xmlMode: true });
    }
}, {
    xmlMode: true
});
let wxmlParser = new Parser(handler);
wxmlParser.write(file);
wxmlParser.end();

**Comment by dhlolo** [comment]
xmlMode should be set in Parser

new Parser(handler, { xmlMode: true })
