### ISSUE TITLE
How to get modified html ?

### ISSUE THREAD

**Issue by dimaslanjaka** [fb55/domhandler#686]
i have modifying all objects from inside function handler. and i want return the modified html. how to get that ?
no complete usage on this documentation and htmlparser2 documentation.

**Comment by fb55** [comment]
Have a look at the `dom-serializer` package!

**Comment by ivanjeremic** [comment]
The whole domhandler/htmlparser2 ecosystem is totally confusing and not well documented.

**Comment by fb55** [comment]
Most of the packages are intended as building blocks for other modules. As a user, I'd have a look at `cheerio`, which provides a more convenient API for all of this.
