### ISSUE TITLE
serializer serializes elements removed through DomUtils

### ISSUE THREAD

**Issue by UltraCakeBakery** [fb55/domhandler#701]
When you parse this code that contains a duplicate HTML element through `parser.parseDocument()`:
```html
<html>
  <body>
      <h1>Foo</h1>
  </body>
</html>

<html>
  <body>
      <h1>Bar</h1>
  </body>
</html>
```

... and run this code over the returned document which removes every html element after the first one...

```javascript
const elements = DomUtils.getChildren(document)

let found = false
for (const child of elements) {
	if (found) {
		DomUtils.removeElement(child)
		continue
	}

	if (child.tagName === 'html') found = true
}
```
The children do not exist on the syntax tree anymore. But if you then serialize the document using `dom-serializer` the last HTML tag is back.

I think this has to do with the `prev` and `next` helper functions still having a reference to the second html element, but I am unable to confirm this as the htmlparser2 playground (https://astexplorer.net/#/2AmVrGuGVJ) is not capable of outputting json and uses version 5.0.1.

I know html documents are not supposed to have more than two elements, that is why I want to remove them automatically.

**Comment by fb55** [comment]
`removeElement` removes the `prev` and `next` references as well: https://github.com/fb55/domutils/blob/ccbca2e3da674b5137c42c29d5b4f278d390207f/src/manipulation.ts#L9-L17

In any case, you might want to have a look at https://github.com/cheeriojs/cheerio for a simpler way of dealing with the DOM (also based on this module).
