### ISSUE TITLE
Updating html-webpack-plugin uses domhanlder 4 and breaking all tests 

### ISSUE THREAD

**Issue by simkessy** [fb55/domhandler#765]
- I updated Webpack from 4 to 5
- This required I update  html-webpack-plugin from v3 to v5
- Now all my Jest v26 tests fail: 
![image](https://user-images.githubusercontent.com/5871660/154550632-e5b2cfb0-80ba-4f40-a54e-1a906f535b9e.png)

I asked in html-webpack-plugin but they were not helpful: 
https://github.com/jantimon/html-webpack-plugin/issues/1733

Do I need to update Jest or something else?

**Comment by fb55** [comment]
Try `rm -rf package-lock.json node_modules; npm install`?

**Comment by simkessy** [comment]
My project is in a mono repo, I think there were conflicts between domhandler versions. I was able to fix this by using `nohoisting` features in yarn workspaces to prevent from running into these conflicts
