### ISSUE TITLE
How to delete an element?

### ISSUE THREAD

**Issue by tonympls** [fb55/domhandler#805]
What is the best way to delete an element? 

Example: Remove the `<book id="bk102">` element from 
```xml
<catalog>
   <book id="bk101">
      <author>Gambardella, Matthew</author>
      <title>XML Developer's Guide</title>
      <genre>Computer</genre>
      <price>44.95</price>
      <publish_date>2000-10-01</publish_date>
      <description>An in-depth look at creating applications 
      with XML.</description>
   </book>
   <book id="bk102">
      <author>Ralls, Kim</author>
      <title>Midnight Rain</title>
      <genre>Fantasy</genre>
      <price>5.95</price>
      <publish_date>2000-12-16</publish_date>
      <description>A former architect battles corporate zombies, 
      an evil sorceress, and her own childhood to become queen 
      of the world.</description>
   </book>
</catalog>
```

**Comment by fb55** [comment]
You most likely want to use `cheerio`, which wraps around `domhandler` and provides simple APIs for modifying the DOM. For your example, you'd want to do:

```js
const $ = cheerio.load(
  '<catalog> ... </catalog>', 
  // If you're not dealing with HTML, use the `xml` option
  {xml: true}
)
$('#bk102').remove()
const result = $.xml() // The updated document, as a string
```

Hope this makes sense!

**Comment by tonympls** [comment]
Oh yes, it definitely makes sense.  I was just hoping I was just missing something and my search for an xml parser ended with `htmlparser2`/`domhandler`.  Are you sure?  All I need is an edit button. :) I'm a package skeptic and was glad to find your packages when the need for an xml parser came up.  Thank you for your quick response and work.

**Comment by fb55** [comment]
You could also use [removeElement](https://domutils.js.org/modules.html#removeElement) from the `domutils` package. Cheerio is the batteries-included approach though, and likely what most users are looking for.

**Comment by tonympls** [comment]
Outstanding.  That's it. Thank you.
