### ISSUE TITLE
TypeError: document.children.find is not a function

### ISSUE THREAD

**Issue by ComLock** [fb55/domhandler#898]
This happens when running serverside.
In my case inside Java Nashorn.
I typically have to Polyfill stuff.
So that might be the case here too.

Going to continue looking for "DOM" polyfills. Any suggestions on the way? :)

**Comment by fb55** [comment]
You will have to polyfill https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find — hope that helps!

**Comment by ComLock** [comment]
It helped :)

import 'core-js/actual/array/find';
import 'core-js/actual/array/find-index';
